# for an example project named 'nextjs-cloud-run'

steps:
  # build the container images
  - name: "gcr.io/cloud-builders/docker"
    args:
      ["build", "-t", "gcr.io/gebirah-14/app", "./gebirah"]

  # push the container images to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/gebirah-14/app"]

  # Deploy container images to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "app",
        "--image",
        "gcr.io/gebirah-14/app",
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--quiet",
        "--allow-unauthenticated",
      ]
images:
  - gebirah-14/app