steps:
  - id: "fetch secrets"
    name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      [
        "-c",
        "export NEXT_PUBLIC_URL=$(gcloud secrets versions access latest --secret=NEXT_PUBLIC_URL) && \
         export NEXT_PUBLIC_FRONTEND=$(gcloud secrets versions access latest --secret=NEXT_PUBLIC_FRONTEND) && \
         echo 'SECRETS fetched'
         "
      ]

  - id: "build image"
    name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args: ["-c", "docker build -t gcr.io/${PROJECT_ID}/${_SERVICE_NAME} . "]

  - id: "push image"
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}"]

  - id: "run deploy"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run", "deploy",
        "${_SERVICE_NAME}",
        "--platform", "managed",
        "--region", "${_REGION}",
        "--image", "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}",
        "--set-env-vars", "NEXT_PUBLIC_URL=${NEXT_PUBLIC_URL}",
        "--set-env-vars", "NEXT_PUBLIC_FRONTEND=${NEXT_PUBLIC_FRONTEND}"
      ]

substitutions:
  _REGION: asia-southeast1
  _SERVICE_NAME: gebirah-frontend

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}"