test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

google_dev:
  service: GCS
  project: gebirah-14
  credentials: { REDACTED, REDACTED, REDACTED, REDACTED, REDACTED, REDACTED,
    REDACTED,
    REDACTED,
    REDACTED,
    REDACTED,
    REDACTED
  }
  bucket: gebirah-bucket

google:
  service: GCS
  project: gebirah-14
  credentials: { REDACTED, REDACTED, REDACTED, REDACTED, REDACTED, REDACTED,
    REDACTED,
    REDACTED,
    REDACTED,
    REDACTED,
    REDACTED
  }
  bucket: gebirah-bucket
